/**
 * Generate a downloadable PDF of a patient's resource submission(s).
 *
 * Layout (per page if needed):
 *   ┌────────────────────────────────────────────────┐
 *   │ Bloomsline logo            [pract avatar/init] │
 *   │                            Practitioner name   │
 *   ├────────────────────────────────────────────────┤
 *   │ Resource title                                 │
 *   │ Submitted by Patient · date                    │
 *   ├────────────────────────────────────────────────┤
 *   │ Q1: ...                                        │
 *   │   answer                                       │
 *   │ ...                                            │
 *   ├────────────────────────────────────────────────┤
 *   │ Practitioner notes (if any)                    │
 *   │ Generated by Bloomsline · 2026-05-07           │
 *   └────────────────────────────────────────────────┘
 *
 * For recurring resources we render every submission in chronological order,
 * separated by a divider.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type { Resource, ResourceBlock } from '@/types/resource'

type Locale = 'en' | 'fr' | 'es'

interface Args {
  supabase: SupabaseClient
  resourceId: string
  memberId: string
  practitionerId: string
  locale: Locale
}

const QUESTION_TYPES = [
  'prompt', 'multiple_choice', 'yes_no', 'checklist', 'scale', 'likert',
  'numeric', 'slider', 'matrix_rating', 'mood', 'date_picker', 'time_input',
  'list_input', 'table_exercise', 'video_response', 'audio_response', 'file_response',
] as const

function getInitials(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean)
  if (parts.length === 0) return '?'
  if (parts.length === 1) return parts[0][0].toUpperCase()
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase()
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function safeFilename(s: string): string {
  return s.replace(/[\\/:*?"<>|]/g, '').replace(/\s+/g, '-').slice(0, 80)
}

function formatDate(iso: string, locale: Locale): string {
  const fmt = locale === 'fr' ? 'fr-FR' : locale === 'es' ? 'es-ES' : 'en-US'
  return new Date(iso).toLocaleDateString(fmt, {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}

/** Render a single answer to plain HTML based on the block type. */
function renderAnswer(block: ResourceBlock, response: unknown, locale: Locale): string {
  const notAnswered = locale === 'fr' ? 'Non renseigné' : locale === 'es' ? 'Sin respuesta' : 'Not answered'
  if (response === undefined || response === null || response === '' ||
      (Array.isArray(response) && response.length === 0) ||
      (typeof response === 'object' && !Array.isArray(response) && Object.keys(response as object).length === 0)) {
    return `<em style="color:#9ca3af">${notAnswered}</em>`
  }

  switch (block.type) {
    case 'prompt':
    case 'numeric':
    case 'slider':
    case 'mood':
    case 'date_picker':
    case 'time_input':
    case 'yes_no':
    case 'multiple_choice':
    case 'scale':
    case 'likert':
      return `<div style="white-space:pre-wrap">${escapeHtml(String(response))}</div>`

    case 'checklist':
    case 'list_input':
      if (Array.isArray(response)) {
        const items = response.map(r => `<li style="margin:2px 0">${escapeHtml(String(r))}</li>`).join('')
        return `<ul style="margin:4px 0;padding-left:20px;list-style:disc">${items}</ul>`
      }
      return `<div>${escapeHtml(String(response))}</div>`

    case 'table_exercise': {
      const cols = ('columns' in block && Array.isArray((block as { columns?: unknown }).columns))
        ? ((block as unknown as { columns: { id: string; header: string }[] }).columns)
        : []
      const rows = Array.isArray(response) ? (response as Record<string, string>[]) : []
      if (rows.length === 0 || cols.length === 0) {
        return `<em style="color:#9ca3af">${notAnswered}</em>`
      }
      const head = cols.map(c => `<th style="text-align:left;padding:6px 8px;background:#f9fafb;border:1px solid #e5e7eb;font-size:11px;color:#6b7280">${escapeHtml(c.header)}</th>`).join('')
      const body = rows.map(r =>
        `<tr>${cols.map(c => `<td style="padding:6px 8px;border:1px solid #e5e7eb;font-size:12px">${escapeHtml(r[c.id] || '-')}</td>`).join('')}</tr>`
      ).join('')
      return `<table style="border-collapse:collapse;width:100%;margin:6px 0"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`
    }

    case 'video_response':
    case 'audio_response':
    case 'file_response': {
      const label = locale === 'fr' ? 'Fichier soumis' : locale === 'es' ? 'Archivo enviado' : 'File submitted'
      return `<em style="color:#6b7280">[${label}]</em>`
    }

    default:
      return `<div style="white-space:pre-wrap">${escapeHtml(String(response))}</div>`
  }
}

function renderSubmissionBlock(
  resource: Resource,
  responses: Record<string, unknown>,
  index: number,
  totalCount: number,
  submittedAt: string | null,
  locale: Locale,
): string {
  const blocks = (resource.blocks || []) as ResourceBlock[]
  const questionBlocks = blocks.filter(b => (QUESTION_TYPES as readonly string[]).includes(b.type))

  const submissionLabel = totalCount > 1
    ? (locale === 'fr' ? `Soumission ${index + 1} sur ${totalCount}` : locale === 'es' ? `Envío ${index + 1} de ${totalCount}` : `Submission ${index + 1} of ${totalCount}`)
    : ''

  const submittedAtLine = submittedAt
    ? `<div style="font-size:11px;color:#6b7280;margin-bottom:14px">${escapeHtml(formatDate(submittedAt, locale))}</div>`
    : ''

  const items = questionBlocks.map((block, i) => {
    const question = (typeof block.content === 'string' && block.content.trim())
      ? block.content
      : `Question ${i + 1}`
    const ans = renderAnswer(block, responses[block.id], locale)
    return `
      <div style="margin-bottom:14px;page-break-inside:avoid">
        <div style="font-size:13px;font-weight:600;color:#111827;margin-bottom:6px">Q${i + 1}. ${escapeHtml(question)}</div>
        <div style="font-size:12px;color:#374151;padding-left:12px;border-left:2px solid #e5e7eb">${ans}</div>
      </div>
    `
  }).join('')

  return `
    <div style="margin-top:${index === 0 ? '0' : '24px'};${index > 0 ? 'border-top:1px dashed #d1d5db;padding-top:18px;' : ''}">
      ${submissionLabel ? `<div style="font-size:12px;font-weight:600;color:#4A9A86;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px">${submissionLabel}</div>` : ''}
      ${submittedAtLine}
      ${items || `<div style="color:#9ca3af;font-style:italic;font-size:12px">${escapeHtml(locale === 'fr' ? 'Aucune question dans cette ressource' : locale === 'es' ? 'No hay preguntas en este recurso' : 'No questions in this resource')}</div>`}
    </div>
  `
}

export async function downloadResourceSubmissionPDF(args: Args): Promise<void> {
  const { supabase, resourceId, memberId, practitionerId, locale } = args

  // Parallel fetch: resource, all submissions, member, practitioner
  const [resourceRes, submissionsRes, memberRes, practitionerRes] = await Promise.all([
    supabase.from('resources').select('*').eq('id', resourceId).maybeSingle(),
    supabase
      .from('resource_responses')
      .select('id, responses, status, submitted_at, created_at, practitioner_notes')
      .eq('resource_id', resourceId)
      .eq('member_id', memberId)
      .eq('practitioner_id', practitionerId)
      .in('status', ['submitted', 'reviewed'])
      .order('submitted_at', { ascending: true }),
    supabase.from('members').select('first_name, last_name').eq('id', memberId).maybeSingle(),
    supabase.from('users').select('full_name, avatar_url').eq('id', practitionerId).maybeSingle(),
  ])

  const resource = resourceRes.data as Resource | null
  const submissions = (submissionsRes.data || []) as Array<{
    id: string
    responses: Record<string, unknown>
    status: string
    submitted_at: string | null
    created_at: string
    practitioner_notes: string | null
  }>
  const member = memberRes.data as { first_name: string; last_name: string } | null
  const practitioner = practitionerRes.data as { full_name: string | null; avatar_url: string | null } | null

  if (!resource) throw new Error('Resource not found')
  if (!member) throw new Error('Member not found')
  if (submissions.length === 0) throw new Error('No submissions to export')

  // Title resolution (resources have a `title` field)
  const resourceTitle = (resource as unknown as { title: string }).title || 'Resource'
  const memberName = `${member.first_name} ${member.last_name}`.trim()
  const practitionerName = practitioner?.full_name || (locale === 'fr' ? 'Praticien' : locale === 'es' ? 'Profesional' : 'Practitioner')
  const practitionerInitials = getInitials(practitionerName)

  const submissionsHtml = submissions.map((s, i) =>
    renderSubmissionBlock(resource, s.responses || {}, i, submissions.length, s.submitted_at || s.created_at, locale)
  ).join('')

  // Practitioner notes — combine across submissions if multiple
  const allNotes = submissions
    .map(s => s.practitioner_notes)
    .filter((n): n is string => !!n && n.trim().length > 0)
  const notesHtml = allNotes.length > 0
    ? `<div style="margin-top:24px;padding:14px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px">
        <div style="font-size:11px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px">${locale === 'fr' ? 'Notes du praticien' : locale === 'es' ? 'Notas del profesional' : 'Practitioner notes'}</div>
        <div style="font-size:12px;color:#374151;white-space:pre-wrap">${allNotes.map(escapeHtml).join('<br><br>')}</div>
       </div>`
    : ''

  // Practitioner avatar — try image, fall back to initials circle
  const avatarHtml = practitioner?.avatar_url
    ? `<img src="${escapeHtml(practitioner.avatar_url)}" crossorigin="anonymous" style="width:40px;height:40px;border-radius:50%;object-fit:cover;display:block" />`
    : `<div style="width:40px;height:40px;border-radius:50%;background:#4A9A86;color:white;display:flex;align-items:center;justify-content:center;font-weight:600;font-size:14px">${escapeHtml(practitionerInitials)}</div>`

  const generatedLabel = locale === 'fr' ? 'Généré par Bloomsline' : locale === 'es' ? 'Generado por Bloomsline' : 'Generated by Bloomsline'
  const submittedByLabel = locale === 'fr' ? 'Soumis par' : locale === 'es' ? 'Enviado por' : 'Submitted by'
  const today = new Date().toLocaleDateString(locale === 'fr' ? 'fr-FR' : locale === 'es' ? 'es-ES' : 'en-US')

  // A4 in mm: 210 x 297. Use 794 x 1123 px @ 96 DPI ratio for DOM.
  const PAGE_W_PX = 794
  const PAD_PX = 48

  const html = `
    <div style="padding:${PAD_PX}px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#111827;background:white;width:${PAGE_W_PX}px;box-sizing:border-box">
      <!-- Header -->
      <div style="display:flex;align-items:center;justify-content:space-between;padding-bottom:18px;border-bottom:2px solid #4A9A86;margin-bottom:24px">
        <div style="font-size:22px;letter-spacing:0.02em;line-height:1;white-space:nowrap">
          <span style="font-weight:500;color:#1F2227">blooms</span><span style="font-weight:300;color:#4A9A86">line</span>
        </div>
        <div style="display:flex;align-items:center;gap:10px">
          ${avatarHtml}
          <div style="text-align:right">
            <div style="font-size:13px;font-weight:600;color:#111827">${escapeHtml(practitionerName)}</div>
            <div style="font-size:11px;color:#6b7280">${escapeHtml(locale === 'fr' ? 'Praticien' : locale === 'es' ? 'Profesional' : 'Practitioner')}</div>
          </div>
        </div>
      </div>

      <!-- Resource title -->
      <div style="margin-bottom:6px;font-size:22px;font-weight:700;color:#111827;line-height:1.3">${escapeHtml(resourceTitle)}</div>
      <div style="margin-bottom:24px;font-size:12px;color:#6b7280">${escapeHtml(submittedByLabel)} <strong>${escapeHtml(memberName)}</strong></div>

      <!-- Submissions -->
      ${submissionsHtml}

      <!-- Notes + footer -->
      ${notesHtml}
      <div style="margin-top:32px;padding-top:14px;border-top:1px solid #e5e7eb;display:flex;justify-content:space-between;align-items:center;font-size:10px;color:#9ca3af">
        <div>${escapeHtml(generatedLabel)}</div>
        <div>${escapeHtml(today)}</div>
      </div>
    </div>
  `

  // Mount off-screen
  const wrapper = document.createElement('div')
  wrapper.style.position = 'fixed'
  wrapper.style.left = '-99999px'
  wrapper.style.top = '0'
  wrapper.innerHTML = html
  document.body.appendChild(wrapper)

  try {
    const target = wrapper.firstElementChild as HTMLElement
    if (!target) throw new Error('Failed to render template')

    // Wait a frame so layout settles
    await new Promise(r => requestAnimationFrame(() => r(null)))

    const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
      import('html2canvas-pro'),
      import('jspdf'),
    ])

    const canvas = await html2canvas(target, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    })

    // A4 portrait, mm
    const PDF_W = 210
    const PDF_H = 297
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

    const imgW = PDF_W
    const imgH = (canvas.height * imgW) / canvas.width
    let heightLeft = imgH
    let position = 0

    const imgData = canvas.toDataURL('image/png')

    pdf.addImage(imgData, 'PNG', 0, position, imgW, imgH)
    heightLeft -= PDF_H

    // Add additional pages if content overflows
    while (heightLeft > 0) {
      position -= PDF_H
      pdf.addPage()
      pdf.addImage(imgData, 'PNG', 0, position, imgW, imgH)
      heightLeft -= PDF_H
    }

    const filename = `${safeFilename(memberName)}_${safeFilename(resourceTitle)}_${new Date().toISOString().slice(0, 10)}.pdf`
    pdf.save(filename)
  } finally {
    document.body.removeChild(wrapper)
  }
}
